### ISSUE TITLE
Update README for latest version

### ISSUE THREAD

**Issue by Darkflib** [alexellis/faas-containerd#15]
There are two minor issues in the readme... 

The first is a missing faas-containerd start in the primary flow.
The second is an omitted container when using ctr to list containers.

## Possible Solution

PR 14 fixes these

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* OS and architecture:

* Versions:

```sh
go version

containerd -version

uname -a

cat /etc/os-release
```

**Comment by alexellis** [comment]
Thanks for testing the project. Please edit the description and use a hash to reference your PR.

**Comment by alexellis** [comment]
I.e. `Fixes: #14`

**Comment by alexellis** [comment]
Closing as fixed in #14

**Comment by alexellis** [comment]
/set title: Update README for latest version

**Comment by Darkflib** [comment]
Sorry about that.. new system with none of my existing aliases :(
