### ISSUE TITLE
Add example to README.md of how to run with auth

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas-containerd#16]
## Description

Add example to README.md of how to run with auth

## Context

In #12 basic_auth support was added, but it wasn't documented.

**Comment by alexellis** [comment]
@LucasRoesler or @Waterdrips could you take this?

**Comment by Waterdrips** [comment]
I'm unlikely to get to do any work today or tomorrow I'm afraid. I could after that?

**Comment by LucasRoesler** [comment]
l am going to give it a quick try now with the basic auth and if it works, write that up, I'll let you know @Waterdrips

**Comment by LucasRoesler** [comment]
wow, i have a hard time keeping this and https://github.com/alexellis/faasd straight in my head, I can definitely add the example for the basic auth here, since I already did it while test it #12

**Comment by alexellis** [comment]
Any suggestions on how we can disambiguate?
