### ISSUE TITLE
Report containers as found in containerd rather than in-memory

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas-containerd#20]
Report containers as found in containerd rather than in-memory

## Expected Behaviour

Any containers with matching tasks and IPs should be reported on the list functions handler.  

## Current Behaviour

We only report from an in-memory map rather than going to containerd.

## Possible Solution

The pattern would be in pseudocode, something like this:

```
def List_containers_and_IPs() :
res = []
cs=  containerd.listcontainers(namespace)
for c in cs:
   t = containerd.get_task(c)
   pid = t.pid
  ip = CNI or Weavenet . GetIP(pid)
  res = append({name: cs.name, ip: ip })
return res
```

This change would mean that containers could survive a restart of faas-containerd, but right now, since we only track in memory, we lose that data when the process starts up again.

Caching may be required if the list function is slow.

If the machine reboots, only the container survives, but not the task and the task is the process with a PID and IP. Therefore if we have only a container and no task, we could report 0/0 replicas and if invoked, scale to 1 should create any missing task.

Scaling to zero is supported in this provider, but the function status endpoint is hard-coded to 1 replica, the above work will fix that and allow 0/0 to be reported when that's the case.

**Comment by alexellis** [comment]
cc @carlosedp

**Comment by carlosedp** [comment]
Been worked on #21

**Comment by alexellis** [comment]
:+1:

**Comment by alexellis** [comment]
Completed
