### ISSUE TITLE
Functions fail to deploy

### ISSUE THREAD

**Issue by utsavanand2** [alexellis/faas-containerd#22]
## Expected Behaviour

The functions should get deployed on a faas deploy invocation

## Current Behaviour

I'm getting 400 status response code from faas-containerd
<img width="1920" alt="Screenshot 2020-01-09 at 12 14 39 PM" src="https://user-images.githubusercontent.com/25264581/72044544-ffda2580-32d9-11ea-8521-b8df5c9af09b.png">

## Possible Solution

It looks like it is still looking for netns not CNI

## Steps to Reproduce (for bugs)

I followed the steps in the README.

## Your Environment

* OS and architecture: Debian 9 stretch

* Versions:

```sh
go version: 
go version go1.12.14 linux/amd64

containerd -version
containerd github.com/containerd/containerd v1.3.2 ff48f57fc83a8c44cf4ad5d672424a98ba37ded6

uname -a
Linux faas-containerd 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by utsavanand2** [comment]
@carlosedp Can you hint me towards what can go wrong here? What can I do to fix this? Thanks 😄

**Comment by alexellis** [comment]
Hi you might have skipped the step for netns

**Comment by alexellis** [comment]
Is it not in the blog post?

**Comment by utsavanand2** [comment]
I've tested the new changes in the [commit](https://github.com/alexellis/faas-containerd/commit/db684985e51558abc5b80a9ce3972d63a3e9980d)

**Comment by utsavanand2** [comment]
Derek close

**Comment by utsavanand2** [comment]
Thank a lot for the help Sir @alexellis 😇It's running fine now
